CREATE TABLE [dbo].[IT14] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [Norma_Id]           INT            NOT NULL,
    [DivisaoOcupacao_Id] INT            NOT NULL,
    [CargaIncendio_Id]   INT            NOT NULL,
    [Descricao]          VARCHAR (1000) NOT NULL,
    [Exemplos]           VARCHAR (1000) NOT NULL,
    [QtdCargaIncendio]   DECIMAL (18)   NOT NULL,
    [Compilado]          VARCHAR (1000) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([CargaIncendio_Id]) REFERENCES [dbo].[CargaIncendio] ([Id]),
    FOREIGN KEY ([CargaIncendio_Id]) REFERENCES [dbo].[CargaIncendio] ([Id]),
    FOREIGN KEY ([CargaIncendio_Id]) REFERENCES [dbo].[CargaIncendio] ([Id]),
    FOREIGN KEY ([CargaIncendio_Id]) REFERENCES [dbo].[CargaIncendio] ([Id]),
    FOREIGN KEY ([CargaIncendio_Id]) REFERENCES [dbo].[CargaIncendio] ([Id]),
    FOREIGN KEY ([CargaIncendio_Id]) REFERENCES [dbo].[CargaIncendio] ([Id]),
    FOREIGN KEY ([CargaIncendio_Id]) REFERENCES [dbo].[CargaIncendio] ([Id]),
    FOREIGN KEY ([CargaIncendio_Id]) REFERENCES [dbo].[CargaIncendio] ([Id]),
    FOREIGN KEY ([CargaIncendio_Id]) REFERENCES [dbo].[CargaIncendio] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id])
);

