CREATE TABLE [dbo].[Protecao] (
    [Id]                   INT IDENTITY (1, 1) NOT NULL,
    [ItemNorma_Id]         INT NOT NULL,
    [Medida_Id]            INT NOT NULL,
    [DescricaoNota_Id]     INT NOT NULL,
    [DivisaoOcupacao_Id]   INT NOT NULL,
    [ParametroOcupacao_Id] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([DescricaoNota_Id]) REFERENCES [dbo].[DescricaoNota] ([Id]),
    FOREIGN KEY ([DescricaoNota_Id]) REFERENCES [dbo].[DescricaoNota] ([Id]),
    FOREIGN KEY ([DescricaoNota_Id]) REFERENCES [dbo].[DescricaoNota] ([Id]),
    FOREIGN KEY ([DescricaoNota_Id]) REFERENCES [dbo].[DescricaoNota] ([Id]),
    FOREIGN KEY ([DescricaoNota_Id]) REFERENCES [dbo].[DescricaoNota] ([Id]),
    FOREIGN KEY ([DescricaoNota_Id]) REFERENCES [dbo].[DescricaoNota] ([Id]),
    FOREIGN KEY ([DescricaoNota_Id]) REFERENCES [dbo].[DescricaoNota] ([Id]),
    FOREIGN KEY ([DescricaoNota_Id]) REFERENCES [dbo].[DescricaoNota] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([DivisaoOcupacao_Id]) REFERENCES [dbo].[DivisaoOcupacao] ([Id]),
    FOREIGN KEY ([ItemNorma_Id]) REFERENCES [dbo].[ItemNorma] ([Id]),
    FOREIGN KEY ([ItemNorma_Id]) REFERENCES [dbo].[ItemNorma] ([Id]),
    FOREIGN KEY ([ItemNorma_Id]) REFERENCES [dbo].[ItemNorma] ([Id]),
    FOREIGN KEY ([ItemNorma_Id]) REFERENCES [dbo].[ItemNorma] ([Id]),
    FOREIGN KEY ([ItemNorma_Id]) REFERENCES [dbo].[ItemNorma] ([Id]),
    FOREIGN KEY ([ItemNorma_Id]) REFERENCES [dbo].[ItemNorma] ([Id]),
    FOREIGN KEY ([ItemNorma_Id]) REFERENCES [dbo].[ItemNorma] ([Id]),
    FOREIGN KEY ([Medida_Id]) REFERENCES [dbo].[Medida] ([Id]),
    FOREIGN KEY ([Medida_Id]) REFERENCES [dbo].[Medida] ([Id]),
    FOREIGN KEY ([Medida_Id]) REFERENCES [dbo].[Medida] ([Id]),
    FOREIGN KEY ([Medida_Id]) REFERENCES [dbo].[Medida] ([Id]),
    FOREIGN KEY ([Medida_Id]) REFERENCES [dbo].[Medida] ([Id]),
    FOREIGN KEY ([Medida_Id]) REFERENCES [dbo].[Medida] ([Id]),
    FOREIGN KEY ([Medida_Id]) REFERENCES [dbo].[Medida] ([Id]),
    FOREIGN KEY ([ParametroOcupacao_Id]) REFERENCES [dbo].[ParametroOcupacao] ([Id]),
    FOREIGN KEY ([ParametroOcupacao_Id]) REFERENCES [dbo].[ParametroOcupacao] ([Id]),
    FOREIGN KEY ([ParametroOcupacao_Id]) REFERENCES [dbo].[ParametroOcupacao] ([Id]),
    FOREIGN KEY ([ParametroOcupacao_Id]) REFERENCES [dbo].[ParametroOcupacao] ([Id]),
    FOREIGN KEY ([ParametroOcupacao_Id]) REFERENCES [dbo].[ParametroOcupacao] ([Id]),
    FOREIGN KEY ([ParametroOcupacao_Id]) REFERENCES [dbo].[ParametroOcupacao] ([Id]),
    FOREIGN KEY ([ParametroOcupacao_Id]) REFERENCES [dbo].[ParametroOcupacao] ([Id])
);

